#! /bin/sh

sxhkd &
~/.fehbg &
./.config/polybar/launch.sh &
. ~/Scripts/brillo.sh &
compton &
#tint2 &
#mx-tweak --tray &
nm-applet &
#pnmixer &
lxpolkit &
xfce4-power-manager &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config top_padding         20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Galculator state=floating
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#a89984"
bspc config presel_feedback_color "#6272a4"

